"""made is_public nullable

Revision ID: 26cd4228b969
Revises: ba3b21d04452
Create Date: 2018-04-15 09:44:39.029695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd4228b969'
down_revision = 'ba3b21d04452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboards', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('queries', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('queries', sa.Column('tag_list', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('queries', sa.Column('url', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_queries_is_public'), 'queries', ['is_public'], unique=False)
    op.create_unique_constraint(None, 'queries', ['url'])
    op.add_column('visualizations', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('visualizations', sa.Column('url', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_visualizations_is_public'), 'visualizations', ['is_public'], unique=False)
    op.create_unique_constraint(None, 'visualizations', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visualizations', type_='unique')
    op.drop_index(op.f('ix_visualizations_is_public'), table_name='visualizations')
    op.drop_column('visualizations', 'url')
    op.drop_column('visualizations', 'is_public')
    op.drop_constraint(None, 'queries', type_='unique')
    op.drop_index(op.f('ix_queries_is_public'), table_name='queries')
    op.drop_column('queries', 'url')
    op.drop_column('queries', 'tag_list')
    op.drop_column('queries', 'is_public')
    op.alter_column('dashboards', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
