"""added a new column in users

Revision ID: 71684850ea1c
Revises: d1eae8b9893e
Create Date: 2018-03-21 15:58:20.542640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71684850ea1c'
down_revision = 'd1eae8b9893e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logged_at')
    # ### end Alembic commands ###
