"""new columns in users and dashboards

Revision ID: ba3b21d04452
Revises: b8d6bdaf5b5a
Create Date: 2018-04-15 09:33:40.031479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3b21d04452'
down_revision = 'b8d6bdaf5b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('description', sa.String(length=4096), nullable=True))
    op.add_column('dashboards', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('dashboards', sa.Column('tag_list', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('dashboards', sa.Column('url', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_dashboards_is_public'), 'dashboards', ['is_public'], unique=False)
    op.create_unique_constraint(None, 'dashboards', ['url'])
    op.create_unique_constraint(None, 'tags', ['url'])
    op.create_unique_constraint(None, 'tags', ['text'])
    op.add_column('users', sa.Column('username', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'dashboards', type_='unique')
    op.drop_index(op.f('ix_dashboards_is_public'), table_name='dashboards')
    op.drop_column('dashboards', 'url')
    op.drop_column('dashboards', 'tag_list')
    op.drop_column('dashboards', 'is_public')
    op.drop_column('dashboards', 'description')
    # ### end Alembic commands ###
