"""added a new table queryresultmetadata

Revision ID: d8a0c6523d9b
Revises: 71684850ea1c
Create Date: 2018-03-22 13:55:54.227517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8a0c6523d9b'
down_revision = '71684850ea1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_results_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_query_ids', sa.String(length=128), nullable=False),
    sa.Column('query_result_id', sa.Integer(), nullable=False),
    sa.Column('data_consumed_mb', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['query_result_id'], ['query_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_results_metadata_query_hash'), 'query_results_metadata', ['query_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_results_metadata_query_hash'), table_name='query_results_metadata')
    op.drop_table('query_results_metadata')
    # ### end Alembic commands ###
