"""added a new colimn run_by_user_id queryresultmetadata

Revision ID: e2fc3bc7d3c7
Revises: d8a0c6523d9b
Create Date: 2018-03-22 14:56:25.465013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fc3bc7d3c7'
down_revision = 'd8a0c6523d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_results_metadata', sa.Column('run_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query_results_metadata', 'users', ['run_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_results_metadata', type_='foreignkey')
    op.drop_column('query_results_metadata', 'run_by_user_id')
    # ### end Alembic commands ###
