"""changed column type of query_id

Revision ID: e434bf850502
Revises: 6eee478c948e
Create Date: 2018-03-20 14:46:32.998706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e434bf850502'
down_revision = '6eee478c948e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_results_metadata', sa.Column('updated_query_ids', sa.String(length=128), nullable=False))
    op.drop_constraint(u'query_results_metadata_query_id_fkey', 'query_results_metadata', type_='foreignkey')
    op.drop_column('query_results_metadata', 'query_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_results_metadata', sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'query_results_metadata_query_id_fkey', 'query_results_metadata', 'queries', ['query_id'], ['id'])
    op.drop_column('query_results_metadata', 'updated_query_ids')
    # ### end Alembic commands ###
