"""added 2 new columns to user database

Revision ID: edea22f0008d
Revises: e2fc3bc7d3c7
Create Date: 2018-03-23 15:22:54.530247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edea22f0008d'
down_revision = 'e2fc3bc7d3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_data_consumed_mb', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.add_column('users', sa.Column('usage_limit_mb', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_limit_mb')
    op.drop_column('users', 'total_data_consumed_mb')
    # ### end Alembic commands ###
